### ISSUE TITLE
Playwright dependency issue

### ISSUE THREAD

**Issue by HansBhatia** [fetchfox/fetchfox#13]
```
node:1872) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/fetch/PlaywrightFetcher.js:66
      await browser.close();
                    ^

TypeError: Cannot read properties of undefined (reading 'close')
    at PlaywrightFetcher._fetch (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/fetch/PlaywrightFetcher.js:66:21)
    at async PlaywrightFetcher.fetch (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/fetch/BaseFetcher.js:52:17)
    at async MinimizingExtractor.getDoc (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/extract/BaseExtractor.js:38:12)
    at async MinimizingExtractor.run (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/extract/MinimizingExtractor.js:18:17)
    at async MinimizingExtractor.stream (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/extract/BaseExtractor.js:141:22)
    at async ExtractStep.process (file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/step/ExtractStep.js:28:22)
    at async file:///Users/hansbhatia/Dev/flights-test/node_modules/.pnpm/fetchfox@0.0.31_@types+node-fetch@2.6.11_zod@3.23.8/node_modules/fetchfox/src/step/BaseStep.js:156:9

Node.js v21.6.1
```

**Comment by HansBhatia** [comment]
`import { fox } from 'fetchfox';

const URL = "https://www.pointhound.com/flights?dateBuffer=false&flightClass=Business+%26+First+Class&originCode=JFK&originName=New+York&destinationCode=BOS&destinationName=Boston&passengerCount=1&departureDate=2024-11-23";

const f = await fox.config({
    fetcher: ['playwright', { headless: true }],
    // diskCache: os.tmpdir() + '/fetchfox-test-cache',
})
    .init(URL)
    .extract({
        pointsRequired: 'How many points are required for this flight?',
        additionalFees: 'What are the additional fees?',
        flightDuration: 'What is the flight duration?',
        numberOfStops: 'What is the number of stops?',
        stopOverDetails: 'What is the stop over details? (if any) where is the stop over? how long is the stop over? give me an array of details',
        airportSourceAITACode: 'What is the airport source AITA code?',
        airportDestinationAITACode: 'What is the airport destination AITA code?',
    })
    .run(null, (partial) => {
        // stuff
        console.log('partial', partial)
    });

console.log(f);`

**Comment by ortutay** [comment]
You need to run `npx playwright install` before using playwright. The library should check for this and give a helpful message.

**Comment by ortutay** [comment]
https://github.com/fetchfox/fetchfox/commit/b69e4e7d7abb0cb2d07102caa1fad7bd9e18d00e
